CREATE DATABASE RegistrationForm;
GO

USE RegistrationForm;
GO

CREATE TABLE Users (
    ID INT PRIMARY KEY IDENTITY(1,1),
    Name NVARCHAR(100) NOT NULL,
    Department NVARCHAR(100) NOT NULL,
	Email NVARCHAR(100) UNIQUE NOT NULL

);

GO
SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Users';